---
title: "T shaped data skills"
author: "Paul Williams"
date: "`r Sys.Date()`"
output: html_document
---

# T-shape data skills

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=TRUE,
  warning=FALSE,
  message=FALSE,
  dev="svg"
)
```

```{r install, results='hide'}
install.packages("tidyverse")
```

### Skill set functions

```{r skillset-functions, results='hide'}
library(tibble)

new_skill_set <- function() {
  data <- tibble(
    name = character(),  # Full name
    label = character(), # Short name for the plot
    level = integer(),   # Scale is your decision but use integers 
  )
  return (data)
}

add_skill <- function(skill_set, name, label, level) {
  skill_set <- skill_set %>% add_row(name, label, level)
  return (skill_set)
}

lock_ordering <- function(skill_set) {
  skill_set$label <- factor(skill_set$label, levels = skill_set$label)
  return (skill_set)
}
```

### T-shape theme

```{r t-shape-theme, results='hide'}
t_shaped_theme <- function() {
  theme(
    panel.background = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none",
  )
}
```

### T-shape plot

```{r t-shape-plot, results='hide'}
library(ggplot2)
library(dplyr)
library(scales)

t_shaped_plot <- function(data) {
  max_level <- max(data$level)
  item_count <- nrow(data)
  
  data %>%
    mutate(fills = rep(c(1:(item_count-1), "top"), 1)) %>%
    ggplot(aes(x=label, y=level, fill=fills)) +
    geom_col(position = position_stack()) +
    scale_y_reverse() +
    scale_x_discrete(position="top") +
    scale_fill_manual(
      values = seq_gradient_pal(
        "lightblue", "darkblue", "Lab"
      )(seq(0,1,length.out=item_count))
      #values = c(
        #colorRampPalette(colors = c("lightblue", "navy"))(max_level+1)
      #)
      # TODO: colour so that each bar is a gradient
      # TODO: https://stackoverflow.com/questions/64016696/ggplot-bars-with-gradient-fill
    ) +
    t_shaped_theme()
}
```

### Domains of expertise

```{r domains-of-expertise}

# The order is important!
# Plotting is left to right from the top of the list.
# We want deep skills in the middle and broad skills distributed equally at
# the sides.
new_skill_set() %>%
  add_skill("Economics", "Econ", 1) %>%
  add_skill("Psychology", "Psy", 1) %>%
  add_skill("Data analytics", "Data", 3) %>%
  add_skill("Software engineering", "Engi", 6) %>%
  add_skill("Leading teams", "Lead", 3) %>%
  add_skill("Graphic design", "Design", 1) %>%
  add_skill("User research & User experience", "UR & UX", 1) %>%
  lock_ordering() %>%
  t_shaped_plot()
```